language: java

jdk: openjdk11


addons:
  sonarcloud:
    organization: "evoi95"
    token: "dbde0ddacf15c805ccd6481347d81d7bbbd76a17" # encrypted value of your token

services:
  - mysql

script:
  - ant build
  - sonar-scanner
