language: java

jdk: openjdk11


before_install:

  - sudo apt install mysql-workbenc

install: true
 

addons:
  sonarcloud:
    organization: "evoi95"
    token: "6d5cec859a4a29bc48708738b7bd9b6a7860273e" # encrypted value of your token

services:
  - mysql

script:
  - ant build
  - sonar-scanner
