language: java

jdk: openjdk11


addons:
  sonarcloud:
    organization: "evoi95"
    token: "071a0adf841bba331df6cdf7df158055beab85c2" # encrypted value of your token

services:
  - mysql

script:
  - ant build
  - sonar-scanner
