language: java

jdk: openjdk11


addons:
  sonarcloud:
    organization: "evoi95"
    token: "103441ca81c0e2144f0e0d5dd7b23de6d85ed208" # encrypted value of your token

services:
  - mysql

script:
  - ant build
  - sonar-scanner
